#!/bin/sh
export LD_LIBRARY_PATH="/tmp" 
cp -f ../../../lib*/*.so* /tmp

host=`uname -n`

echo "starting Naming Service daemon ..."
nsd -ORBIIOPAddr inet:$host:12456 &
nsd_pid=$!

trap "kill $nsd_pid" 0
sleep 2

echo "starting ilogger(pgsqllogd) server ..."
#ulimit -c 132234
../../../core/pgsql/pgsqllogd \
-ORBInitRef NameService=corbaloc::$host:12456/NameService . &
server_pid=$!

trap "kill $nsd_pid $server_pid" 0
sleep 2

echo "running client ..."
./ilogger -ORBInitRef NameService=corbaloc::$host:12456/NameService 
#gdb ilogger
