#-----------------------------------------------------------------------
# Copyright IONA Technologies 2002-2004. All rights reserved.
# This software is provided "as is".
#-----------------------------------------------------------------------
BASE=../../..

include ../../Makefile.unix.inc

#--------
# Lists of files used by make rules.
#--------
OBJ =		PoaUtility.o

#--------
# Rules
#--------

default:	all

all:		$(OBJ)

clean:
	-rm -f *.o

install:
