#-----------------------------------------------------------------------
# Copyright IONA Technologies 2002-2003. All rights reserved.
# This software is provided "as is".
#-----------------------------------------------------------------------


#--------
# Uncomment one of the following lines, depending on which
# CORBA product you are using.
#--------

!include "Makefile.inc.orbix"
#!include "Makefile.inc.orbacus"
#!include "Makefile.inc.tao"
#!include "Makefile.inc.omniorb"
