#!/bin/sh
exec 2>&1
export PROG=qmailvqd

if [ -f /etc/sysconfig/vq ] ; then
	. /etc/sysconfig/vq
	[ -n "$VQ_HOME" ] && export VQ_HOME || unset VQ_HOME
	[ -n "$VQ_ETC_DIR" ] && export VQ_ETC_DIR || unset VQ_ETC_DIR
fi

if [ ! -z "$VQ_HOME" ] ; then
    export PATH="$PATH":"$VQ_HOME"
fi

if [ ! -d $VQ_HOME ] ; then
    echo "VQ_HOME not set!"
    exit 1
fi

# for omniORB
args="-ORBendPoint \"giop:unix:/var/vq/sockets/$PROG.sock\""

# for MICO
#args="-ORBIIOPAddr \"unix:/var/vq/sockets/$PROG.sock\""

exec su _vq -c "exec "$PROG" $args \
-ORBInitRef NameService=corbaloc::127.0.0.1:2809/NameService \
$VQ_HOME"
