package com.foo_baz.v_q;


/**
* com/foo_baz/v_q/_ivqStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/new/svn/berlios.de/v-q/trunk/base/logger.idl
* poniedzia³ek, 6 marzec 2006 22:05:07 CET
*/


/*@}*/
public class _ivqStub extends org.omg.CORBA.portable.ObjectImpl implements com.foo_baz.v_q.ivq
{


  /// Add domain
  public com.foo_baz.v_q.ivqPackage.error dom_add (String dom, org.omg.CORBA.IntHolder dom_id) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("dom_add", true);
                $out.write_string (dom);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                dom_id.value = com.foo_baz.v_q.ivqPackage.id_typeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return dom_add (dom, dom_id        );
            } finally {
                _releaseReply ($in);
            }
  } // dom_add


  /// Removes domain
  public com.foo_baz.v_q.ivqPackage.error dom_rm (int dom_id) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("dom_rm", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return dom_rm (dom_id        );
            } finally {
                _releaseReply ($in);
            }
  } // dom_rm


  /// Validates domain name
  public com.foo_baz.v_q.ivqPackage.error dom_val (String dom) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("dom_val", true);
                $out.write_string (dom);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return dom_val (dom        );
            } finally {
                _releaseReply ($in);
            }
  } // dom_val


  /// Gets ID of domain
  public com.foo_baz.v_q.ivqPackage.error dom_id (String dom, org.omg.CORBA.IntHolder dom_id) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("dom_id", true);
                $out.write_string (dom);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                dom_id.value = com.foo_baz.v_q.ivqPackage.id_typeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return dom_id (dom, dom_id        );
            } finally {
                _releaseReply ($in);
            }
  } // dom_id


  /// Gets name of a domain
  public com.foo_baz.v_q.ivqPackage.error dom_name (int dom_id, org.omg.CORBA.StringHolder dom_name) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("dom_name", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                dom_name.value = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return dom_name (dom_id, dom_name        );
            } finally {
                _releaseReply ($in);
            }
  } // dom_name


  /// List all domains
  public com.foo_baz.v_q.ivqPackage.error dom_ls (com.foo_baz.v_q.ivqPackage.domain_info_listHolder dis) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("dom_ls", true);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                dis.value = com.foo_baz.v_q.ivqPackage.domain_info_listHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return dom_ls (dis        );
            } finally {
                _releaseReply ($in);
            }
  } // dom_ls


  /// add alias for a domain
  public com.foo_baz.v_q.ivqPackage.error da_add (int dom_id, String ali) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("da_add", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                $out.write_string (ali);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return da_add (dom_id, ali        );
            } finally {
                _releaseReply ($in);
            }
  } // da_add


  /// Removes alias
  public com.foo_baz.v_q.ivqPackage.error da_rm (String ali) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("da_rm", true);
                $out.write_string (ali);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return da_rm (ali        );
            } finally {
                _releaseReply ($in);
            }
  } // da_rm


  /// Lists all aliases for a domain
  public com.foo_baz.v_q.ivqPackage.error da_ls_by_dom (int dom_id, com.foo_baz.v_q.ivqPackage.string_listHolder alis) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("da_ls_by_dom", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                alis.value = com.foo_baz.v_q.ivqPackage.string_listHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return da_ls_by_dom (dom_id, alis        );
            } finally {
                _releaseReply ($in);
            }
  } // da_ls_by_dom


  /// add IP address for a domain
  public com.foo_baz.v_q.ivqPackage.error dip_add (int dom_id, String ip) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("dip_add", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                $out.write_string (ip);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return dip_add (dom_id, ip        );
            } finally {
                _releaseReply ($in);
            }
  } // dip_add


  /// Removes IP address
  public com.foo_baz.v_q.ivqPackage.error dip_rm (String ip) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("dip_rm", true);
                $out.write_string (ip);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return dip_rm (ip        );
            } finally {
                _releaseReply ($in);
            }
  } // dip_rm


  /// Lists all IP addresses for a domain
  public com.foo_baz.v_q.ivqPackage.error dip_ls_by_dom (int dom_id, com.foo_baz.v_q.ivqPackage.string_listHolder ips) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("dip_ls_by_dom", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                ips.value = com.foo_baz.v_q.ivqPackage.string_listHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return dip_ls_by_dom (dom_id, ips        );
            } finally {
                _releaseReply ($in);
            }
  } // dip_ls_by_dom


  /// Adds user
  public com.foo_baz.v_q.ivqPackage.error user_add (com.foo_baz.v_q.ivqPackage.user_info ai, boolean is_banned) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("user_add", true);
                com.foo_baz.v_q.ivqPackage.user_infoHelper.write ($out, ai);
                $out.write_boolean (is_banned);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return user_add (ai, is_banned        );
            } finally {
                _releaseReply ($in);
            }
  } // user_add


  /// Modify user
  public com.foo_baz.v_q.ivqPackage.error user_rep (com.foo_baz.v_q.ivqPackage.user_info ui, boolean password, boolean dir) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("user_rep", true);
                com.foo_baz.v_q.ivqPackage.user_infoHelper.write ($out, ui);
                $out.write_boolean (password);
                $out.write_boolean (dir);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return user_rep (ui, password, dir        );
            } finally {
                _releaseReply ($in);
            }
  } // user_rep


  /// Removes user
  public com.foo_baz.v_q.ivqPackage.error user_rm (int dom_id, String login) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("user_rm", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                $out.write_string (login);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return user_rm (dom_id, login        );
            } finally {
                _releaseReply ($in);
            }
  } // user_rm


  /// Changes password
  public com.foo_baz.v_q.ivqPackage.error user_pass (int dom_id, String login, String pass) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("user_pass", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                $out.write_string (login);
                $out.write_string (pass);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return user_pass (dom_id, login, pass        );
            } finally {
                _releaseReply ($in);
            }
  } // user_pass


  /// Checks if user name is valid (not if user exists)
  public com.foo_baz.v_q.ivqPackage.error user_val (String user) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("user_val", true);
                $out.write_string (user);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return user_val (user        );
            } finally {
                _releaseReply ($in);
            }
  } // user_val


  /// Gets informations about user
  public com.foo_baz.v_q.ivqPackage.error user_get (com.foo_baz.v_q.ivqPackage.user_infoHolder ai) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("user_get", true);
                com.foo_baz.v_q.ivqPackage.user_infoHelper.write ($out, ai.value);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                ai.value = com.foo_baz.v_q.ivqPackage.user_infoHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return user_get (ai        );
            } finally {
                _releaseReply ($in);
            }
  } // user_get


  /// Checks whether user exists
  public com.foo_baz.v_q.ivqPackage.error user_ex (int dom_id, String login) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.except, com.foo_baz.v_q.db_error
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("user_ex", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                $out.write_string (login);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return user_ex (dom_id, login        );
            } finally {
                _releaseReply ($in);
            }
  } // user_ex


  /// get all users in specified domain
  public com.foo_baz.v_q.ivqPackage.error user_ls_by_dom (int dom_id, int start, int cnt, com.foo_baz.v_q.ivqPackage.user_info_listHolder uis) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("user_ls_by_dom", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                com.foo_baz.v_q.ivqPackage.size_typeHelper.write ($out, start);
                com.foo_baz.v_q.ivqPackage.size_typeHelper.write ($out, cnt);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                uis.value = com.foo_baz.v_q.ivqPackage.user_info_listHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return user_ls_by_dom (dom_id, start, cnt, uis        );
            } finally {
                _releaseReply ($in);
            }
  } // user_ls_by_dom


  /// get number of users in specified domain
  public com.foo_baz.v_q.ivqPackage.error user_cnt_by_dom (int dom_id, org.omg.CORBA.IntHolder cnt) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("user_cnt_by_dom", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                cnt.value = com.foo_baz.v_q.ivqPackage.size_typeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return user_cnt_by_dom (dom_id, cnt        );
            } finally {
                _releaseReply ($in);
            }
  } // user_cnt_by_dom


  //@{
  public com.foo_baz.v_q.ivqPackage.error eb_add (String re_domain, String re_login) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eb_add", true);
                $out.write_string (re_domain);
                $out.write_string (re_login);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eb_add (re_domain, re_login        );
            } finally {
                _releaseReply ($in);
            }
  } // eb_add

  public com.foo_baz.v_q.ivqPackage.error eb_rm (String re_domain, String re_login) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eb_rm", true);
                $out.write_string (re_domain);
                $out.write_string (re_login);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eb_rm (re_domain, re_login        );
            } finally {
                _releaseReply ($in);
            }
  } // eb_rm

  public com.foo_baz.v_q.ivqPackage.error eb_ls (com.foo_baz.v_q.ivqPackage.email_banned_listHolder ebs) throws com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eb_ls", true);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                ebs.value = com.foo_baz.v_q.ivqPackage.email_banned_listHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eb_ls (ebs        );
            } finally {
                _releaseReply ($in);
            }
  } // eb_ls


  /// Adds mailbox configuration
  public com.foo_baz.v_q.ivqPackage.error user_conf_add (int dom_id, String user, String pfix, com.foo_baz.v_q.ivqPackage.user_conf_infoHolder ui) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("user_conf_add", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                $out.write_string (user);
                $out.write_string (pfix);
                com.foo_baz.v_q.ivqPackage.user_conf_infoHelper.write ($out, ui.value);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                ui.value = com.foo_baz.v_q.ivqPackage.user_conf_infoHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return user_conf_add (dom_id, user, pfix, ui        );
            } finally {
                _releaseReply ($in);
            }
  } // user_conf_add


  /// Removes all mailbox configuration entries
  public com.foo_baz.v_q.ivqPackage.error user_conf_rm_by_type (int dom_id, String user, String pfix, short ut) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("user_conf_rm_by_type", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                $out.write_string (user);
                $out.write_string (pfix);
                com.foo_baz.v_q.ivqPackage.user_conf_typeHelper.write ($out, ut);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return user_conf_rm_by_type (dom_id, user, pfix, ut        );
            } finally {
                _releaseReply ($in);
            }
  } // user_conf_rm_by_type


  /// Removes mailbox configuration entry
  public com.foo_baz.v_q.ivqPackage.error user_conf_rm (int dom_id, String user, String pfix, int id) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("user_conf_rm", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                $out.write_string (user);
                $out.write_string (pfix);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, id);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return user_conf_rm (dom_id, user, pfix, id        );
            } finally {
                _releaseReply ($in);
            }
  } // user_conf_rm


  /// Lists mailbox configuration
  public com.foo_baz.v_q.ivqPackage.error user_conf_ls (int dom_id, String user, String pfix, com.foo_baz.v_q.ivqPackage.user_conf_info_listHolder uis) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("user_conf_ls", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                $out.write_string (user);
                $out.write_string (pfix);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                uis.value = com.foo_baz.v_q.ivqPackage.user_conf_info_listHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return user_conf_ls (dom_id, user, pfix, uis        );
            } finally {
                _releaseReply ($in);
            }
  } // user_conf_ls


  /// Lists mailbox configuation of specified type
  public com.foo_baz.v_q.ivqPackage.error user_conf_ls_by_type (int dom_id, String user, String pfix, short ut, com.foo_baz.v_q.ivqPackage.user_conf_info_listHolder uis) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("user_conf_ls_by_type", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                $out.write_string (user);
                $out.write_string (pfix);
                com.foo_baz.v_q.ivqPackage.user_conf_typeHelper.write ($out, ut);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                uis.value = com.foo_baz.v_q.ivqPackage.user_conf_info_listHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return user_conf_ls_by_type (dom_id, user, pfix, ut, uis        );
            } finally {
                _releaseReply ($in);
            }
  } // user_conf_ls_by_type


  /// Changes existing entry
  public com.foo_baz.v_q.ivqPackage.error user_conf_rep (int dom_id, String user, String pfix, com.foo_baz.v_q.ivqPackage.user_conf_info ui) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("user_conf_rep", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                $out.write_string (user);
                $out.write_string (pfix);
                com.foo_baz.v_q.ivqPackage.user_conf_infoHelper.write ($out, ui);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return user_conf_rep (dom_id, user, pfix, ui        );
            } finally {
                _releaseReply ($in);
            }
  } // user_conf_rep


  /// Gets existing entry
  public com.foo_baz.v_q.ivqPackage.error user_conf_get (com.foo_baz.v_q.ivqPackage.user_conf_infoHolder ui) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("user_conf_get", true);
                com.foo_baz.v_q.ivqPackage.user_conf_infoHelper.write ($out, ui.value);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                ui.value = com.foo_baz.v_q.ivqPackage.user_conf_infoHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return user_conf_get (ui        );
            } finally {
                _releaseReply ($in);
            }
  } // user_conf_get


  /// Checks whether mailbox has entry of specified type
  public com.foo_baz.v_q.ivqPackage.error user_conf_type_has (int dom_id, String user, String pfix, short ut) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("user_conf_type_has", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                $out.write_string (user);
                $out.write_string (pfix);
                com.foo_baz.v_q.ivqPackage.user_conf_typeHelper.write ($out, ut);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return user_conf_type_has (dom_id, user, pfix, ut        );
            } finally {
                _releaseReply ($in);
            }
  } // user_conf_type_has


  /// Counts entries of specified type
  public com.foo_baz.v_q.ivqPackage.error user_conf_type_cnt (int dom_id, String user, String pfix, short ut, org.omg.CORBA.IntHolder cnt) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("user_conf_type_cnt", true);
                com.foo_baz.v_q.ivqPackage.id_typeHelper.write ($out, dom_id);
                $out.write_string (user);
                $out.write_string (pfix);
                com.foo_baz.v_q.ivqPackage.user_conf_typeHelper.write ($out, ut);
                $in = _invoke ($out);
                com.foo_baz.v_q.ivqPackage.error $result = com.foo_baz.v_q.ivqPackage.errorHelper.read ($in);
                cnt.value = com.foo_baz.v_q.ivqPackage.size_typeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:vq/null_error:1.0"))
                    throw com.foo_baz.v_q.null_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/db_error:1.0"))
                    throw com.foo_baz.v_q.db_errorHelper.read ($in);
                else if (_id.equals ("IDL:vq/except:1.0"))
                    throw com.foo_baz.v_q.exceptHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return user_conf_type_cnt (dom_id, user, pfix, ut, cnt        );
            } finally {
                _releaseReply ($in);
            }
  } // user_conf_type_cnt

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:vq/ivq:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _ivqStub
