package com.foo_baz.v_q;


/**
* com/foo_baz/v_q/db_error.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../logger.idl
* piątek, 17 marzec 2006 20:09:52 CET
*/

public final class db_error extends org.omg.CORBA.UserException
{
  public String what = null;
  public String file = null;
  public int line = (int)0;

  public db_error ()
  {
    super(db_errorHelper.id());
  } // ctor

  public db_error (String _what, String _file, int _line)
  {
    super(db_errorHelper.id());
    what = _what;
    file = _file;
    line = _line;
  } // ctor


  public db_error (String $reason, String _what, String _file, int _line)
  {
    super(db_errorHelper.id() + "  " + $reason);
    what = _what;
    file = _file;
    line = _line;
  } // ctor

} // class db_error
