package com.foo_baz.v_q;


/**
* com/foo_baz/v_q/except.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/new/svn/berlios.de/v-q/trunk/base/logger.idl
* poniedzia³ek, 6 marzec 2006 22:05:07 CET
*/

public final class except extends org.omg.CORBA.UserException
{
  public String what = null;
  public String file = null;
  public int line = (int)0;

  public except ()
  {
    super(exceptHelper.id());
  } // ctor

  public except (String _what, String _file, int _line)
  {
    super(exceptHelper.id());
    what = _what;
    file = _file;
    line = _line;
  } // ctor


  public except (String $reason, String _what, String _file, int _line)
  {
    super(exceptHelper.id() + "  " + $reason);
    what = _what;
    file = _file;
    line = _line;
  } // ctor

} // class except
