package com.foo_baz.v_q;


/**
* com/foo_baz/v_q/iauth.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/pniewiad/Desktop/personal/projects/v-q/trunk/base/auth.idl
* Wednesday, December 14, 2005 9:01:52 PM CET
*/


/**
	 * Base class representing authorization module.
	 */
public interface iauth extends iauthOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface iauth
