package com.foo_baz.v_q;


/**
* com/foo_baz/v_q/iauth.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/new/svn/berlios.de/v-q/trunk/base/auth.idl
* poniedzia³ek, 6 marzec 2006 22:05:03 CET
*/


/**
	 * Base class representing authorization module.
	 */
public interface iauth extends iauthOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface iauth
