package com.foo_baz.v_q;

/**
* com/foo_baz/v_q/iauthHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/pniewiad/Desktop/personal/projects/v-q/trunk/base/auth.idl
* Wednesday, December 14, 2005 9:01:52 PM CET
*/


/**
	 * Base class representing authorization module.
	 */
public final class iauthHolder implements org.omg.CORBA.portable.Streamable
{
  public com.foo_baz.v_q.iauth value = null;

  public iauthHolder ()
  {
  }

  public iauthHolder (com.foo_baz.v_q.iauth initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.foo_baz.v_q.iauthHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.foo_baz.v_q.iauthHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.foo_baz.v_q.iauthHelper.type ();
  }

}
