package com.foo_baz.v_q;


/**
* com/foo_baz/v_q/iauth.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../auth.idl
* piątek, 17 marzec 2006 20:09:44 CET
*/


/**
	 * Base class representing authorization module.
	 */
public interface iauth extends iauthOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface iauth
