package com.foo_baz.v_q;


/**
* com/foo_baz/v_q/iloggerPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/pniewiad/Desktop/personal/projects/v-q/trunk/base/logger.idl
* Wednesday, December 14, 2005 9:01:53 PM CET
*/


/**
	 * Base class for subsystem responsible of storing informations about
	 * users' loggins.
	 */
public class iloggerPOATie extends iloggerPOA
{

  // Constructors

  public iloggerPOATie ( com.foo_baz.v_q.iloggerOperations delegate ) {
      this._impl = delegate;
  }
  public iloggerPOATie ( com.foo_baz.v_q.iloggerOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public com.foo_baz.v_q.iloggerOperations _delegate() {
      return this._impl;
  }
  public void _delegate (com.foo_baz.v_q.iloggerOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }

  /// Clears all settings
  public void clear () throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
    _impl.clear();
  } // clear


  /// sets client address
  public void ip_set (String ip) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
    _impl.ip_set(ip);
  } // ip_set


  /// set service type
  public void service_set (short ser) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
    _impl.service_set(ser);
  } // service_set


  /// set domain
  public void domain_set (String dom) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
    _impl.domain_set(dom);
  } // domain_set


  /// set user
  public void login_set (String log) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
    _impl.login_set(log);
  } // login_set


  /// Write information
  public com.foo_baz.v_q.ivqPackage.error write (short r, String msg) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
    return _impl.write(r, msg);
  } // write


  /**
			 * Read all entries from global log (log table)
			 * \param start 0 means first entry
			 * \param cnt number of rows that should be read (can be less returned)
			 */
  public com.foo_baz.v_q.ivqPackage.error read (int start, int cnt, com.foo_baz.v_q.iloggerPackage.log_entry_listHolder les) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
    return _impl.read(start, cnt, les);
  } // read


  /**
			 * Count all entries from global log table
			 */
  public com.foo_baz.v_q.ivqPackage.error count (org.omg.CORBA.IntHolder cnt) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
    return _impl.count(cnt);
  } // count


  /**
			 * Read all entries for domain. In this case res[i].domain will be
			 * empty.
			 */
  public com.foo_baz.v_q.ivqPackage.error read_by_dom (int start, int cnt, com.foo_baz.v_q.iloggerPackage.log_entry_listHolder les) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
    return _impl.read_by_dom(start, cnt, les);
  } // read_by_dom


  /**
			 * Count all entries for domain.
			 */
  public com.foo_baz.v_q.ivqPackage.error count_by_dom (org.omg.CORBA.IntHolder cnt) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
    return _impl.count_by_dom(cnt);
  } // count_by_dom


  /**
			 * Read all entries for login@domain. In this case res[i].domain
			 * and res[i].login will be empty.
			 */
  public com.foo_baz.v_q.ivqPackage.error read_by_user (int start, int cnt, com.foo_baz.v_q.iloggerPackage.log_entry_listHolder les) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
    return _impl.read_by_user(start, cnt, les);
  } // read_by_user


  /**
			 * Count all entries for login@domain
			 */
  public com.foo_baz.v_q.ivqPackage.error count_by_user (org.omg.CORBA.IntHolder cnt) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
    return _impl.count_by_user(cnt);
  } // count_by_user


  /**
			 * Removes all entries from log table.
			 */
  public com.foo_baz.v_q.ivqPackage.error rm_all () throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
    return _impl.rm_all();
  } // rm_all


  /**
			 * Removes all entries for a domain.
			 */
  public com.foo_baz.v_q.ivqPackage.error rm_by_dom () throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
    return _impl.rm_by_dom();
  } // rm_by_dom


  /**
			 * Removes all entries for a user.
			 */
  public com.foo_baz.v_q.ivqPackage.error rm_by_user () throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except
  {
    return _impl.rm_by_user();
  } // rm_by_user

  private com.foo_baz.v_q.iloggerOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class iloggerPOATie
