package com.foo_baz.v_q;


/**
* com/foo_baz/v_q/ilogger.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/pniewiad/Desktop/personal/projects/v-q/trunk/base/logger.idl
* Wednesday, December 14, 2005 9:01:53 PM CET
*/


/**
	 * Base class for subsystem responsible of storing informations about
	 * users' loggins.
	 */
public interface ilogger extends iloggerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{

  /// what we're logging about
  public static final short ser_unknown = (short)(0);

  //!< unknown connection
  public static final short ser_smtp = (short)(1);

  //!< smpt connection
  public static final short ser_pop3 = (short)(2);

  //!< pop3 connection
  public static final short ser_http = (short)(3);

  //!< http connection
  public static final short ser_https = (short)(4);

  //!< https connection
  public static final short ser_emtp = (short)(5);

  //!< my emtp protocol
  public static final short ser_external = (short)(127);

  /// status of authorization/login
  public static final short re_unknown = (short)(0);
  public static final short re_ok = (short)(1);

  //!< success
  public static final short re_read = (short)(2);

  //!< can't read data
  public static final short re_data = (short)(3);

  //!< invalid data (domain, username, password)
  public static final short re_pass = (short)(4);

  //!< invalid password, description includes given password
  public static final short re_int = (short)(5);

  //!< internal error
  public static final short re_blk = (short)(6);

  //!< user's blocked
  public static final short re_external = (short)(127);
} // interface ilogger
