package com.foo_baz.v_q;


/**
* com/foo_baz/v_q/iloggerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/pniewiad/Desktop/personal/projects/v-q/trunk/base/logger.idl
* Wednesday, December 14, 2005 9:01:53 PM CET
*/


/**
	 * Base class for subsystem responsible of storing informations about
	 * users' loggins.
	 */
public interface iloggerOperations 
{

  /// Clears all settings
  void clear () throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except;

  /// sets client address
  void ip_set (String ip) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except;

  /// set service type
  void service_set (short ser) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except;

  /// set domain
  void domain_set (String dom) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except;

  /// set user
  void login_set (String log) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except;

  /// Write information
  com.foo_baz.v_q.ivqPackage.error write (short r, String msg) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except;

  /**
			 * Read all entries from global log (log table)
			 * \param start 0 means first entry
			 * \param cnt number of rows that should be read (can be less returned)
			 */
  com.foo_baz.v_q.ivqPackage.error read (int start, int cnt, com.foo_baz.v_q.iloggerPackage.log_entry_listHolder les) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except;

  /**
			 * Count all entries from global log table
			 */
  com.foo_baz.v_q.ivqPackage.error count (org.omg.CORBA.IntHolder cnt) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except;

  /**
			 * Read all entries for domain. In this case res[i].domain will be
			 * empty.
			 */
  com.foo_baz.v_q.ivqPackage.error read_by_dom (int start, int cnt, com.foo_baz.v_q.iloggerPackage.log_entry_listHolder les) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except;

  /**
			 * Count all entries for domain.
			 */
  com.foo_baz.v_q.ivqPackage.error count_by_dom (org.omg.CORBA.IntHolder cnt) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except;

  /**
			 * Read all entries for login@domain. In this case res[i].domain
			 * and res[i].login will be empty.
			 */
  com.foo_baz.v_q.ivqPackage.error read_by_user (int start, int cnt, com.foo_baz.v_q.iloggerPackage.log_entry_listHolder les) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except;

  /**
			 * Count all entries for login@domain
			 */
  com.foo_baz.v_q.ivqPackage.error count_by_user (org.omg.CORBA.IntHolder cnt) throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except;

  /**
			 * Removes all entries from log table.
			 */
  com.foo_baz.v_q.ivqPackage.error rm_all () throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except;

  /**
			 * Removes all entries for a domain.
			 */
  com.foo_baz.v_q.ivqPackage.error rm_by_dom () throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except;

  /**
			 * Removes all entries for a user.
			 */
  com.foo_baz.v_q.ivqPackage.error rm_by_user () throws com.foo_baz.v_q.null_error, com.foo_baz.v_q.db_error, com.foo_baz.v_q.except;
} // interface iloggerOperations
