package com.foo_baz.v_q;

/**
* com/foo_baz/v_q/iloggerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/new/svn/berlios.de/v-q/trunk/base/logger.idl
* poniedzia³ek, 6 marzec 2006 22:05:09 CET
*/


/**
	 * Base class for subsystem responsible of storing informations about
	 * users' loggins.
	 */
public final class iloggerHolder implements org.omg.CORBA.portable.Streamable
{
  public com.foo_baz.v_q.ilogger value = null;

  public iloggerHolder ()
  {
  }

  public iloggerHolder (com.foo_baz.v_q.ilogger initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.foo_baz.v_q.iloggerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.foo_baz.v_q.iloggerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.foo_baz.v_q.iloggerHelper.type ();
  }

}
