package com.foo_baz.v_q;

/**
* com/foo_baz/v_q/ivqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../logger.idl
* piątek, 17 marzec 2006 20:09:53 CET
*/


/*@}*/
public final class ivqHolder implements org.omg.CORBA.portable.Streamable
{
  public com.foo_baz.v_q.ivq value = null;

  public ivqHolder ()
  {
  }

  public ivqHolder (com.foo_baz.v_q.ivq initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.foo_baz.v_q.ivqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.foo_baz.v_q.ivqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.foo_baz.v_q.ivqHelper.type ();
  }

}
