package com.foo_baz.v_q;

/**
* com/foo_baz/v_q/ivqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/new/svn/berlios.de/v-q/trunk/base/logger.idl
* poniedzia³ek, 6 marzec 2006 22:05:08 CET
*/


/*@}*/
public final class ivqHolder implements org.omg.CORBA.portable.Streamable
{
  public com.foo_baz.v_q.ivq value = null;

  public ivqHolder ()
  {
  }

  public ivqHolder (com.foo_baz.v_q.ivq initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.foo_baz.v_q.ivqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.foo_baz.v_q.ivqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.foo_baz.v_q.ivqHelper.type ();
  }

}
