/*
Virtual Qmail (http://v-q.foo-baz.com)
Copyright (C) 2002-2004 Pawel Niewiadomski (new-baz.com)

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

#include "vq.idl"

module vq {
	/**
	 * Base class representing authorization module.
	 */
	interface iauth {
			/// Type used for size specifications, the same as in cvq
			typedef ivq::size_type size_type;
			typedef ivq::quota_type quota_type;
			typedef ivq::string_list string_list;
			typedef ivq::auth_info auth_info;
			typedef ivq::udot_info udot_info;
			typedef ivq::udot_info_list udot_info_list;
			typedef ivq::udot_type udot_type;
			typedef ivq::aif_type aif_type;
			typedef ivq::email_banned email_banned;
			typedef ivq::email_banned_list email_banned_list;
			typedef ivq::domain_re_alias domain_re_alias;
			typedef ivq::domain_re_alias_list domain_re_alias_list;
			typedef ivq::err_code err_code;
			typedef ivq::error error;

		/**
		 * \defgroup dom Domains manipulation
		 */
		//@{
			/// Adds domain to database
			error dom_add(in string dom, out string dom_id)
					raises (null_error, db_error, except);
			/// Removes domain.
			error dom_rm(in string dom_id)
					raises (null_error, db_error, except);
			/// Translates domain name to id.
			error dom_id(in string dom, out string did)
					raises (null_error, db_error, except);
			error dom_name(in string dom_id, out string domain)
					raises (null_error, db_error, except);
		//@}
		/**
		 * \defgroup dra Domains REGEX aliases
		 */
		//@{
			/// Adds domain's IP address
			error dra_add(in string dom_id, in string rea)
					raises (null_error, db_error, except);
			/// Remove IP for domain
			error dra_rm(in string dom_id, in string rea)
					raises (null_error, db_error, except);
			/// Removes all IP addresses asociated with domain
			error dra_rm_by_dom(in string dom_id)
					raises (null_error, db_error, except);
			/// Lists all IP addresses asociated with domain
			error dra_ls_by_dom(in string dom_id, out string_list rea)
					raises (null_error, db_error, except);
			/*
			/// Lists domains having IP addresses
			error dra_ip_ls_dom(out string_list doms)
					raises (null_error);
			*/
		//@}
		
		/**
		 * \defgroup user Users manipulation
		 */
		//@{
			/// Adds user
			error user_add(in auth_info ai, in boolean is_banned )
					raises (null_error, db_error, except);
			/// Removes user
			error user_rm(in string dom_id, in string login)
					raises (null_error, db_error, except);
			/// Changes password for user
			error user_pass(in string dom_id, in string login, in string pass )
					raises (null_error, db_error, except);
			/// Gets authorization information for user
			error user_auth( inout auth_info ai )
					raises (null_error, db_error, except);
			/// check if user exists (err_noent if not, err_no if exists)
			error user_ex( in string dom_id, in string login )
					raises (null_error, db_error, except);
		//@}
		/**
		 * \defgroup eb Emails banned
		 */
		//@{
			error eb_add(in string re_domain, in string re_login)
					raises (null_error, db_error, except );
			error eb_rm(in string re_domain, in string re_login)
					raises (null_error, db_error, except );
			error eb_ls(out email_banned_list ebs)
					raises (db_error, except);
		//@}
		/**
		 * \ingroup qt_user
		 */
		//@{
			/// Gets limits for user
			error qt_user_get(in string dom_id, in string user_id, 
					out quota_type bytes_max , out quota_type files_max )
					raises (null_error, db_error, except);
			/// Sets limits for user
			error qt_user_set(in string dom_id, in string user_id, 
					in quota_type bytes_max, in quota_type files_max )
					raises (null_error, db_error, except);
			/// Sets default value for a domain
			error qt_user_def_set(in string dom_id, 
					in quota_type bytes_max, in quota_type files_max )
					raises (null_error, db_error, except);
			/// Gets default value
			error qt_user_def_get(in string dom_id, 
					out quota_type bytes_max, out quota_type files_max )
					raises (null_error, db_error, except);
		//@}
#if 0
		/**
		 * \defgroup udot Mailboxes configuration
		 */
		//@{
			/// Adds mailbox configuration
			error udot_add(in string dom_id, in string user,
					in string pfix, inout udot_info ui )
					raises (null_error, db_error, except);
			/// Removes all mailbox configuration entries
			error udot_rm_by_type(in string dom_id, in string user,
					in string pfix, in udot_type ut )
					raises (null_error, db_error, except);
			/// Removes mailbox configuration entry
			error udot_rm( in string id )
					raises (null_error, db_error, except);
			/// Lists mailbox configuration
			error udot_ls(in string dom_id, in string user,
					in string pfix, out udot_info_list uis )
					raises (null_error, db_error, except);
			/// Lists mailbox configuation of specified type
			error udot_ls_by_type(in string dom_id, in string user,
					in string pfix, in udot_type ut,
					out udot_info_list uis )
					raises (null_error, db_error, except);
			/// Changes existing entry
			error udot_rep( in udot_info ui )
					raises (null_error, db_error, except);
			/// Gets existing entry
			error udot_get(	inout udot_info ui )
					raises (null_error, db_error, except);
			/// Checks whether mailbox has entry of specified type
			error udot_type_has(in string dom_id, in string user,
					in string pfix, in udot_type ut )
					raises (null_error, db_error, except);
			/// Counts entries of specified type
			error udot_type_cnt(in string dom_id, in string user,
					in string pfix, in udot_type ut, 
					out size_type cnt )
					raises (null_error, db_error, except);
		//@}
		
		/**
		 * \ingroup err
		 */
		/*@{*/
			/// return additional information about error (i.e. file name)
			string err_info() 
					raises(except);
			long err_sys()
					raises(except); //!< Returns stored errno

			/// return description of error from lastret
			string err_report()
					raises(except);
		/*@}*/
#endif // if 0
	}; // interface iauth

}; // module vq

