/*
Virtual Qmail (http://v-q.foo-baz.com)
Copyright (C) 2002-2004 Pawel Niewiadomski (new-baz.com)

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/
module vq {
	 
	/**
	 * Wrapper for std::exception
	 */
	exception except {
			string what;
			string file;
			unsigned long line;
	};

	/**
	 * Database error
	 */
	exception db_error {
			string what;
			string file;
			unsigned long line;
	};
	 
	/**
	 * Argument was NULL but it's not allowed
	 */
	 exception null_error {
	 		string file;
			unsigned long line;
	 };
	/*@}*/


	interface ivq {
			typedef unsigned long quota_type; //!< Type for holding quota values
			typedef unsigned long size_type; //!< Type for holding sizes
			typedef unsigned short aif_type;
			typedef unsigned short udot_type;
			typedef sequence<string> string_list;

		/**
		 * \ingroup err
		 */
		/*@{*/
			enum err_code {
					/// no error
					err_no,  // 0
					/// temporary error
					err_temp, // 1
					/// invalid domain name
					err_dom_inv,
					/// invalid user name
					err_user_inv, // 3
					/// user not found
					err_user_nf, 
					/// error in authorization module
					err_auth, // 5
					/// dot file - type is not supported
					err_udot_tns,
					/// can't open sth
					err_open, //  7
					/// can't write
					err_wr,
					/// can't read
					err_rd, // 9
					/// can't stat
					err_stat,
					/// not a directory
					err_notdir, // 11
					/// chmod failed
					err_chmod,
					/// file's locked
					err_lckd, // 13
					/// can't rename
					err_ren,
					/// can't change owner
					err_chown, // 15
					/// overflow
					err_over,
					/// child crashed or returned something unexpected
					err_exec, // 17
					/// can't create directory
					err_mkdir,
					/// entry exists
					err_exists, // 19
					/// no such element/entry
					err_noent,
					/// can't remove
					err_unlink, // 21
					/// invalid password
					err_pass_inv, 
					/// internal function returned unexpected value
					err_func_res
			};

			/// errors
			struct error {
					err_code ec; //!< code
					string what; //!< description
					string file; //!< source file
					unsigned long line; //!< line number
					boolean auth; //!< is this from authorization db?
			};
		/*@}*/
				
			/// possible user account flags
			/// was:
			/// enum auth_info_flags {
			/// blocked pop3 access
			const aif_type aif_pop3_blk = 1;
			/// blocked smtp access
			const aif_type aif_smtp_blk = 2;
			/// admin (it was first added user)
			const aif_type aif_admin = 4;
			/// ftp access blocked
			const aif_type aif_ftp_blk = 8;
			/// ignore me (entry MUST be ignored)
			const aif_type aif_ignore = 16;
			/// super (server) admin
			const aif_type aif_supadm = 32;
			/// };

			/**
			 * structure used in some routines. it includes basic
			 * user's information.
			 */
			struct auth_info {
					string id_domain; //!< domain
					string login;
					string pass; //!< password
					string dir; //!< mailbox directory
					aif_type flags; //!< additional flags
			};

			/// Mailbox options
			const udot_type ut_redir = 1; //!< redirection
			const udot_type ut_maildir = 2; //!< maildir
			const udot_type ut_autoresp = 3; //!< autorespond

			/// user's dot file info
			struct udot_info {
					string id_conf; //!< identificator
					string val; //!< value
					udot_type type; //!< type of entry
			};
			typedef sequence<udot_info> udot_info_list;

			/// banned emails
			struct email_banned {
					string re_domain; //!< POSIX regular exp.
					string re_login; //!< POSIX regulat exp.
			};
			typedef sequence<email_banned> email_banned_list;

			/// domains REGEX aliases
			struct domain_re_alias {
					string id_domain;
					string re_alias;
			};
			typedef sequence<domain_re_alias> domain_re_alias_list;

		/**
		 * \defgroup dom Playing with domains
		 */
		 //@{
			/// Add domain
			error dom_add(in string dom, out string dom_id) 
					raises (null_error, except, db_error); 
			/// Removes domain
			error dom_rm(in string dom_id)
					raises (null_error, except, db_error);
			/// Validates domain name
			error dom_val(in string dom)
					raises (null_error, except, db_error);
			/// Gets ID of domain
			error dom_id(in string dom, out string dom_id)
					raises (null_error, except, db_error);
			/// Gets name of a domain
			error dom_name(in string dom_id, out string dom_name )
					raises (null_error, except, db_error);
		//@}
#if 0
		/**
		 * \defgroup dra Domains REGEX aliases
		 */
		//@{
			error dra_add(in string dom_id, in string rea)
					raises (null_error, except);
			/// Removes IP address
			error dra_rm(in string dom_id, in string rea)
					raises (null_error, except);
			/// Removes all IP addresses
			error dra_rm_by_dom(in string dom_id)
					raises (null_error, except);
		//@}
#endif // if 0
		/**
		 * \defgroup user User handling
		 * @{
		 */
			/// Adds user
			error user_add(in auth_info ai, in boolean is_banned )
					raises (null_error, except, db_error);
			/// Removes user
			error user_rm(in string dom_id, in string login)
					raises (null_error, except, db_error);
			/// Changes password
			error user_pass(in string dom_id, in string login, in string pass)
					raises (null_error, except, db_error);
			/// Checks if user name is valid (not if user exists)
			error user_val(in string user)
					raises (null_error, except, db_error);
			/// Gets authorization info. for user
			error user_auth(inout auth_info ai)
					raises (null_error, except, db_error);
			/// Checks whether user exists
			error user_ex(in string dom_id, in string login)
					raises (null_error, except, db_error);
		//@}

		/**
		 * \defgroup eb Emails banned
		 */
		//@{
			error eb_add(in string re_domain, in string re_login)
					raises (null_error, db_error, except );
			error eb_rm(in string re_domain, in string re_login)
					raises (null_error, db_error, except );
			error eb_ls(out email_banned_list ebs)
					raises (db_error, except);
		//@}

	/**
	 * \defgroup qt Quota support
	 * @{
	 */
		/**
		 * \defgroup qt_user Quota support for users
		 * \ingroup qt
		 */
		//@{
#if 0
			/// Parses string into quota_types
			error qt_parse( in string qts, 
				out quota_type bytes_max, out quota_type files_max )
					raises (null_error, except);
			/// Adds value to current usage
			error qt_cur_set(const string&, 
					in string, int32_t)
					raises (null_error, except);
			/// Checks if over quota
			error qt_over(in string, 
					in string)
					raises (null_error, except);
			/// Sets limits
			error qt_set(in string dom, in string user, 
					out quota_type bytes_max, out quota_type files_max )
					raises (null_error, except);
			/// Gets limits
			error qt_get(in string dom, in string user, 
					out quota_type bytes_max, out quota_type files_max )
					raises (null_error, except);

			/// Sets default value for a domain
			error qt_def_set(in string dom, 
					in quota_type bytes_max, in quota_type files_max )
					raises (null_error, except);
			/// Gets default value
			error qt_def_get(in string dom, 
					out quota_type bytes_max, out quota_type files_max )
					raises (null_error, except);

			/// Sets global defaults for new domains
			error qt_global_def_set( 
					in quota_type bytes_max, in quota_type files_max )
					raises (null_error, except);
			/// Gets global defaults for new domains
			error qt_global_def_get(
					out quota_type bytes_max, out quota_type files_max )
					raises (null_error, except);
		//@}
	/*@}*/

	/**
	 * \defgroup udot Playing with user mailbox's options
	 * @{
	 */
			/// Adds to dot file
			error udot_add(in string dom, in string user,
					in string pfix, inout udot_info ui )
					raises (null_error, except);
			/// Adds some default configuration to user's mailbox
			error udot_add_md_def(in string dom, in string user,
					in string pfix)
					raises (null_error, except);
			/// Removes all options of specified type
			error udot_rm_by_type(in string dom, in string user,
					in string pfix, in udot_type ut )
					raises (null_error, except);
			/// Removes option with given id
			error udot_rm_by_id(in string dom, in string user, 
					in string id)
					raises (null_error, except);
			/// Lists mailbox configuration
			error udot_ls(in string dom, in string user, in string pfix, 
					out udot_info_list uis )
					raises (null_error, except);
			/// Lists mailbox options of specified type
			error udot_ls_by_type(in string dom, in string user,
					in string pfix, in udot_type ut, 
					out udot_info_list uis )
					raises (null_error, except);
			/// Changes value of option with given id.
			error udot_rep(in string dom, in string user,
					in udot_info ui )
					raises (null_error, except);
			/// Gets value of options with given id.
			error udot_get( in string dom, in string user,
					inout udot_info ui )
					raises (null_error, except);
			/// Checks if given option is supported
			error udot_sup_is( in udot_type ut )
					raises (null_error, except);
			/// Checks if mailbox has configured option of given type
			error udot_type_has(in string dom, in string user, in string pfix, 
					in udot_type ut )
					raises (null_error, except);
			/// Counts options with given type
			error udot_type_cnt(in string dom, in string user, in string pfix, 
					in udot_type ut, out size_type cnt )
					raises (null_error, except);
		//@}
#endif // if 0
	}; // interface ivq

}; // module vq
