#!/bin/sh

export LD_LIBRARY_PATH="/tmp" 
cp -f ../../../lib*/*.so* /tmp

host=`uname -n`

echo "starting Naming Service daemon ..."
nsd -ORBIIOPAddr inet:$host:12456 &
nsd_pid=$!

trap "kill $nsd_pid" 0
sleep 1

echo "starting iauth(pgsqlauthd) server ..."
../../../core/pgsql/pgsqlauthd \
-ORBInitRef NameService=corbaloc::$host:12456/NameService . &
iauth_pid=$!
trap "kill $nsd_pid $iauth_pid" 0
sleep 1

echo -ORBInitRef NameService=corbaloc::$host:12453/NameService > etc/ivq/auth
echo "starting ivq(qmailvqd) server ..."
../../../core/qmailvqd/qmailvqd \
-ORBInitRef NameService=corbaloc::$host:12456/NameService . &
ivq_pid=$!

trap "kill $nsd_pid $iauth_pid $ivq_pid" 0
sleep 1

echo "running client ..."
./qmailvqd -ORBInitRef NameService=corbaloc::$host:12456/NameService
