#!/bin/sh
export BASE=../../..
export LD_LIBRARY_PATH="/tmp" 
cp -f $BASE/lib*/*.so* /tmp

host=localhost
prog=ilogger
use_orb=mico

ldd $prog | grep omni > /dev/null
if [ $? = 0 ] ; then
	use_orb=omni
fi

echo "starting Naming Service daemon ..."
if [ $use_orb = mico ] ; then
	nsd -ORBIIOPAddr inet:$host:2809 &
else
	rm -rf omninames-*
	omniNames -start -logdir `pwd` -ORBendPoint giop:tcp:$host:2809 &
fi
nsd_pid=$!

trap "kill $nsd_pid" 0
sleep 2

echo "starting ilogger(pgsqllogd) server ..."
$BASE/base/pgsql/pgsqllogd \
-ORBInitRef NameService=corbaloc::$host:2809/NameService . &
server_pid=$!

trap "kill $nsd_pid $server_pid" 0
sleep 2

echo "running client ..."
./ilogger -ORBInitRef NameService=corbaloc::$host:2809/NameService \
name_service#Logger.ilogger $@
#gdb ilogger

rm -rf omninames-*
