package com.foo_baz.v_q.ivqPackage;


/**
* com/foo_baz/v_q/ivqPackage/domain_info.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../logger.idl
* piątek, 17 marzec 2006 20:09:55 CET
*/


/// domains
public final class domain_info implements org.omg.CORBA.portable.IDLEntity
{
  public int id_domain = (int)0;
  public String domain = null;

  public domain_info ()
  {
  } // ctor

  public domain_info (int _id_domain, String _domain)
  {
    id_domain = _id_domain;
    domain = _domain;
  } // ctor

} // class domain_info
