package com.foo_baz.v_q.ivqPackage;


/**
* com/foo_baz/v_q/ivqPackage/err_codeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../logger.idl
* piątek, 17 marzec 2006 20:09:54 CET
*/


/*@{*/
abstract public class err_codeHelper
{
  private static String  _id = "IDL:vq/ivq/err_code:1.0";

  public static void insert (org.omg.CORBA.Any a, com.foo_baz.v_q.ivqPackage.err_code that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.foo_baz.v_q.ivqPackage.err_code extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (com.foo_baz.v_q.ivqPackage.err_codeHelper.id (), "err_code", new String[] { "err_no", "err_temp", "err_dom_inv", "err_user_inv", "err_auth", "err_user_conf_tns", "err_open", "err_wr", "err_rd", "err_stat", "err_notdir", "err_chmod", "err_lckd", "err_ren", "err_chown", "err_over", "err_exec", "err_mkdir", "err_exists", "err_noent", "err_unlink", "err_pass_inv", "err_func_res", "err_func_ni", "err_exec_crash", "err_perm"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.foo_baz.v_q.ivqPackage.err_code read (org.omg.CORBA.portable.InputStream istream)
  {
    return com.foo_baz.v_q.ivqPackage.err_code.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.foo_baz.v_q.ivqPackage.err_code value)
  {
    ostream.write_long (value.value ());
  }

}
