package com.foo_baz.v_q.ivqPackage;


/**
* com/foo_baz/v_q/ivqPackage/err_code.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/new/svn/berlios.de/v-q/trunk/base/logger.idl
* poniedzia³ek, 6 marzec 2006 22:05:08 CET
*/


/*@{*/
public class err_code implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 26;
  private static com.foo_baz.v_q.ivqPackage.err_code[] __array = new com.foo_baz.v_q.ivqPackage.err_code [__size];

  public static final int _err_no = 0;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_no = new com.foo_baz.v_q.ivqPackage.err_code(_err_no);
  public static final int _err_temp = 1;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_temp = new com.foo_baz.v_q.ivqPackage.err_code(_err_temp);
  public static final int _err_dom_inv = 2;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_dom_inv = new com.foo_baz.v_q.ivqPackage.err_code(_err_dom_inv);
  public static final int _err_user_inv = 3;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_user_inv = new com.foo_baz.v_q.ivqPackage.err_code(_err_user_inv);
  public static final int _err_auth = 4;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_auth = new com.foo_baz.v_q.ivqPackage.err_code(_err_auth);
  public static final int _err_user_conf_tns = 5;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_user_conf_tns = new com.foo_baz.v_q.ivqPackage.err_code(_err_user_conf_tns);
  public static final int _err_open = 6;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_open = new com.foo_baz.v_q.ivqPackage.err_code(_err_open);
  public static final int _err_wr = 7;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_wr = new com.foo_baz.v_q.ivqPackage.err_code(_err_wr);
  public static final int _err_rd = 8;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_rd = new com.foo_baz.v_q.ivqPackage.err_code(_err_rd);
  public static final int _err_stat = 9;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_stat = new com.foo_baz.v_q.ivqPackage.err_code(_err_stat);
  public static final int _err_notdir = 10;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_notdir = new com.foo_baz.v_q.ivqPackage.err_code(_err_notdir);
  public static final int _err_chmod = 11;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_chmod = new com.foo_baz.v_q.ivqPackage.err_code(_err_chmod);
  public static final int _err_lckd = 12;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_lckd = new com.foo_baz.v_q.ivqPackage.err_code(_err_lckd);
  public static final int _err_ren = 13;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_ren = new com.foo_baz.v_q.ivqPackage.err_code(_err_ren);
  public static final int _err_chown = 14;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_chown = new com.foo_baz.v_q.ivqPackage.err_code(_err_chown);
  public static final int _err_over = 15;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_over = new com.foo_baz.v_q.ivqPackage.err_code(_err_over);
  public static final int _err_exec = 16;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_exec = new com.foo_baz.v_q.ivqPackage.err_code(_err_exec);
  public static final int _err_mkdir = 17;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_mkdir = new com.foo_baz.v_q.ivqPackage.err_code(_err_mkdir);
  public static final int _err_exists = 18;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_exists = new com.foo_baz.v_q.ivqPackage.err_code(_err_exists);
  public static final int _err_noent = 19;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_noent = new com.foo_baz.v_q.ivqPackage.err_code(_err_noent);
  public static final int _err_unlink = 20;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_unlink = new com.foo_baz.v_q.ivqPackage.err_code(_err_unlink);
  public static final int _err_pass_inv = 21;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_pass_inv = new com.foo_baz.v_q.ivqPackage.err_code(_err_pass_inv);
  public static final int _err_func_res = 22;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_func_res = new com.foo_baz.v_q.ivqPackage.err_code(_err_func_res);
  public static final int _err_func_ni = 23;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_func_ni = new com.foo_baz.v_q.ivqPackage.err_code(_err_func_ni);
  public static final int _err_exec_crash = 24;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_exec_crash = new com.foo_baz.v_q.ivqPackage.err_code(_err_exec_crash);
  public static final int _err_perm = 25;
  public static final com.foo_baz.v_q.ivqPackage.err_code err_perm = new com.foo_baz.v_q.ivqPackage.err_code(_err_perm);

  public int value ()
  {
    return __value;
  }

  public static com.foo_baz.v_q.ivqPackage.err_code from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected err_code (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class err_code
