package com.foo_baz.v_q.ivqPackage;


/**
* com/foo_baz/v_q/ivqPackage/user_conf_info.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/new/svn/berlios.de/v-q/trunk/base/logger.idl
* poniedzia³ek, 6 marzec 2006 22:05:08 CET
*/

public final class user_conf_info implements org.omg.CORBA.portable.IDLEntity
{
  public int id_conf = (int)0;

  //!< identificator
  public String val = null;

  //!< value
  public short type = (short)0;

  public user_conf_info ()
  {
  } // ctor

  public user_conf_info (int _id_conf, String _val, short _type)
  {
    id_conf = _id_conf;
    val = _val;
    type = _type;
  } // ctor

} // class user_conf_info
