#!/bin/sh
export BASE=../../..
export LD_LIBRARY_PATH="/tmp" 
cp -f $BASE/lib*/*.so* /tmp

host=localhost

echo "starting Naming Service daemon ..."
nsd -ORBIIOPAddr inet:$host:12456 &
nsd_pid=$!

trap "kill $nsd_pid" 0
sleep 2

echo "starting ilogger(pgsqllogd) server ..."
$BASE/base/pgsql/pgsqllogd \
-ORBIIOPAddr inet:$host:34343 \
-ORBInitRef NameService=corbaloc::$host:12456/NameService . &
server_pid=$!

trap "kill $nsd_pid $server_pid" 0
sleep 2

echo "running client ..."
./ilogger -ORBInitRef NameService=corbaloc::$host:12456/NameService $@
#gdb ilogger
