#!/bin/sh

export BASE=../../..
export VQ_HOME=.
export VQ_ETC_DIR=etc

export LD_LIBRARY_PATH="/tmp" 
cp -f $BASE/lib*/*.so* /tmp

export host=localhost
export port=2809
export prog=./ilogger

use_orb=mico

ldd $prog | grep omni > /dev/null
if [ $? = 0 ] ; then
	use_orb=omni
fi

echo "starting Naming Service daemon ..."
if [ $use_orb = mico ] ; then
	nsd -ORBIIOPAddr inet:$host:$port &
else
	rm -rf omninames-*
	omniNames -start -logdir `pwd` -ORBendPoint giop:tcp:$host:$port &
fi
nsd_pid=$!

trap "kill $nsd_pid" 0
sleep 2

for ilogger in ../ilogger.* ; do
	ilogger_name=`basename $ilogger`
	./run.test "$ilogger_name" "$ilogger" "$prog"
done

rm -rf omninames-*
