#!/bin/sh
exec 2>&1
prog="jdbclogd"

if [ ! -z "$VQ_HOME" ] ; then
    export PATH="$PATH":"$VQ_HOME"
else
    export VQ_HOME=`which "$PROG" | xargs dirname | xargs dirname`
    if [ ! -d $VQ_HOME ] ; then
        export VQ_HOME=/var/vq
    fi
fi

if [ ! -d $VQ_HOME ] ; then
    echo "VQ_HOME not set!"
    exit 1
fi

# JDBC drivers 
# add "org.postgresql.Driver" for PostgreSQL
drivers="org.postgresql.Driver"

# add options for your JDBC driver
export CLASSPATH="pg74.215.jdbc3.jar"

# v-q jars
export CLASSPATH="$CLASSPATH":"$VQ_HOME/bin/corbautil.jar":"$VQ_HOME/bin/jdbcd.jar"

java -Djdbc.drivers="$drivers" \
-Dcom.foo_baz.v_q."$prog".jdbc=jdbc:postgresql://localhost/mail \
"$prog" -ORBInitRef NameService=corbaloc::127.0.0.1:2809/NameService

