package com.foo_baz.v_q.iloggerPackage;


/**
* com/foo_baz/v_q/iloggerPackage/log_entry_listHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/pniewiad/Desktop/personal/projects/v-q/trunk/base/logger.idl
* Wednesday, December 14, 2005 9:01:53 PM CET
*/

public final class log_entry_listHolder implements org.omg.CORBA.portable.Streamable
{
  public com.foo_baz.v_q.iloggerPackage.log_entry value[] = null;

  public log_entry_listHolder ()
  {
  }

  public log_entry_listHolder (com.foo_baz.v_q.iloggerPackage.log_entry[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.foo_baz.v_q.iloggerPackage.log_entry_listHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.foo_baz.v_q.iloggerPackage.log_entry_listHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.foo_baz.v_q.iloggerPackage.log_entry_listHelper.type ();
  }

}
