package com.foo_baz.v_q.iloggerPackage;


/**
* com/foo_baz/v_q/iloggerPackage/log_entry.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../logger.idl
* piątek, 17 marzec 2006 20:09:57 CET
*/


/// information stored in log db
public final class log_entry implements org.omg.CORBA.portable.IDLEntity
{
  public String id_log = null;

  //!< entry's id
  public String time = null;

  //!< time when entry was stored
  public short ser = (short)0;

  //!< service
  public String msg = null;

  //!< error message?
  public String login = null;

  //!< user's id
  public String domain = null;

  //!< domain
  public String ip = null;

  //!< client's ip
  public short res = (short)0;

  public log_entry ()
  {
  } // ctor

  public log_entry (String _id_log, String _time, short _ser, String _msg, String _login, String _domain, String _ip, short _res)
  {
    id_log = _id_log;
    time = _time;
    ser = _ser;
    msg = _msg;
    login = _login;
    domain = _domain;
    ip = _ip;
    res = _res;
  } // ctor

} // class log_entry
