package com.foo_baz.v_q.iloggerPackage;


/**
* com/foo_baz/v_q/iloggerPackage/log_entry_listHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/pniewiad/Desktop/personal/projects/v-q/trunk/base/logger.idl
* Wednesday, December 14, 2005 9:01:53 PM CET
*/

abstract public class log_entry_listHelper
{
  private static String  _id = "IDL:vq/ilogger/log_entry_list:1.0";

  public static void insert (org.omg.CORBA.Any a, com.foo_baz.v_q.iloggerPackage.log_entry[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.foo_baz.v_q.iloggerPackage.log_entry[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = com.foo_baz.v_q.iloggerPackage.log_entryHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (com.foo_baz.v_q.iloggerPackage.log_entry_listHelper.id (), "log_entry_list", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.foo_baz.v_q.iloggerPackage.log_entry[] read (org.omg.CORBA.portable.InputStream istream)
  {
    com.foo_baz.v_q.iloggerPackage.log_entry value[] = null;
    int _len0 = istream.read_long ();
    value = new com.foo_baz.v_q.iloggerPackage.log_entry[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = com.foo_baz.v_q.iloggerPackage.log_entryHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.foo_baz.v_q.iloggerPackage.log_entry[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      com.foo_baz.v_q.iloggerPackage.log_entryHelper.write (ostream, value[_i0]);
  }

}
