package com.foo_baz.v_q.iloggerPackage;


/**
* com/foo_baz/v_q/iloggerPackage/service_type_listHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../logger.idl
* piątek, 17 marzec 2006 20:09:57 CET
*/

public final class service_type_listHolder implements org.omg.CORBA.portable.Streamable
{
  public short value[] = null;

  public service_type_listHolder ()
  {
  }

  public service_type_listHolder (short[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.foo_baz.v_q.iloggerPackage.service_type_listHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.foo_baz.v_q.iloggerPackage.service_type_listHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.foo_baz.v_q.iloggerPackage.service_type_listHelper.type ();
  }

}
