#!/bin/sh
exec 2>&1
export PROG=user_auth

if [ -f /etc/sysconfig/vq ] ; then
	. /etc/sysconfig/vq
	[ -n "$VQ_HOME" ] && export VQ_HOME || unset VQ_HOME
	[ -n "$VQ_ETC_DIR" ] && export VQ_ETC_DIR || unset VQ_ETC_DIR
fi

if [ ! -z "$VQ_HOME" ] ; then
    export PATH="$PATH":"$VQ_HOME"
fi

if [ ! -d $VQ_HOME ] ; then
    echo "VQ_HOME not set!"
    exit 1
fi

con=40
if [ -f /var/qmail/control/concurrencypop3d ]; then
    con="`cat /var/qmail/control/concurrencypop3d`"
fi

exec tcpserver -c "$con" -RHv 0 110 qmail-popup \
"`hostname`.`domainname`" "$PROG" \
qmail-pop3d Maildir
