#!/bin/sh
export PROG=user_auth

if [ ! -z "$VQ_HOME" ] ; then
    export PATH="$PATH":"$VQ_HOME"
else
    export VQ_HOME=`which "$PROG" | xargs dirname | xargs dirname`
    if [ ! -d $VQ_HOME ] ; then
        export VQ_HOME=/var/vq
    fi
fi

if [ ! -d $VQ_HOME ] ; then
    echo "VQ_HOME not set!"
    exit 1
fi

exec 2>&1

con=40
if [ -f /var/qmail/control/concurrencypop3d ]; then
    con="`cat /var/qmail/control/concurrencypop3d`"
fi

exec tcpserver -c "$con" -RHv 0 110 qmail-popup \
"`hostname`.`domainname`" "$PROG" \
qmail-pop3d Maildir
