.auto:
	mkdir -p auto

#################
.depend: $(BASE)/compile $(BASE)/tools/mkdep *.cc
	CC=$(BASE)/compile $(BASE)/tools/mkdep $(INCS) *.cc >> .depend 
	if [ -e .depend -a ! -s .depend ]; then \
		rm -f .depend ; \
	fi
