#!/bin/sh
export BASE=../../..
export VQ_HOME=.

rm -rf domains qmail/users/assign qmail/control/locals.lock \
qmail/control/rcpthosts qmail/control/rcpthosts.lock \
qmail/control/virtualdomains qmail/control/virtualdomains.lock

for p in qmail_virtualdomains_add qmail_rcpthosts_add qmail_assign_add \
qmail_locals_rm qmail_file_add qmail_file_rm qmail_mrh_rm \
qmail_virtualdomains_rm qmail_assign_rm qmail_run; do
	ln -sf $BASE/../base/qmailvqd/$p bin
done

export LD_LIBRARY_PATH="/tmp" 
cp -f $BASE/lib*/*.so* /tmp

host=`uname -n`

echo "starting Naming Service daemon ..."
nsd -ORBIIOPAddr inet:$host:12456 &
nsd_pid=$!

trap "kill $nsd_pid" 0
sleep 2

echo "starting iauth(pgsqlauthd) server ..."
$BASE/base/pgsql/pgsqlauthd \
-ORBInitRef NameService=corbaloc::$host:12456/NameService . &
iauth_pid=$!
trap "kill $nsd_pid $iauth_pid" 0
sleep 2

echo `pwd` > etc/ivq/qmail/data
echo -ORBInitRef NameService=corbaloc::$host:12453/NameService > etc/ivq/auth
echo "starting ivq(qmailvqd) server ..."
$BASE/base/qmailvqd/qmailvqd \
-ORBInitRef NameService=corbaloc::$host:12456/NameService . &
ivq_pid=$!

trap "kill $nsd_pid $iauth_pid $ivq_pid" 0
sleep 2

echo "running tests ..."
echo -ORBInitRef NameService=corbaloc::$host:12456/NameService > etc/ivq/orb_conf

for p in `ls [0-9]*.pl | sort -i` ; do
	./$p
done
